apiVersion: v1
kind: Service
metadata:
  name: bhaviyn-clo835-service
spec:
  type: NodePort
  selector:
    app: bhaviyn-clo835-app
  ports:
  - protocol: TCP
    port: 3030
    targetPort: 3030
    nodePort: 32000
